name: unittest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unittest:
    runs-on: ubuntu-20.04
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make dev
      - name: Test
        run: pytest --cov=client_throttler
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
