name: unittest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unittest:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup redis
        uses: supercharge/redis-github-action@1.6.0
        with:
          redis-version: 6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make dev
      - name: Test
        run: pytest --cov=client_throttler
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
